- name: copy limits.conf file
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: clean all file in /etc/security/limits.d
  shell:
    cmd: "sudo rm -rf /etc/security/limits.d/*"
