---
- hosts: dev-node-exporter
  user: root
  # become: true
  gather_facts: no
  tasks:
    - name: Stop and disable node_exporter service
      service:
        name:    node_exporter.service
        enabled: no
        state:   stopped
      register: node_exporter_service_result
      failed_when: "node_exporter_service_result is failed and 'Could not find the requested service' not in node_exporter_service_result.msg"

    - name: Remove node_exporter systemd file
      file:
        path: /etc/systemd/system/node_exporter.service
        state: absent

    - name: Remove node_exporter bin file 
      file:
        #state: absent
        path: /usr/local/bin/node_exporter

    - name: Remove node_exporter data on disk (Dangerous !!!!!!!!!!!!!!!!!)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/node_exporter/
