apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter-ext
  name: node-exporter-ext
spec:
  clusterIP: None
  ports:
    - name: http-9100
      port: 9100
      protocol: TCP
      targetPort: http-9100
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
