- name: stop {{ service_name }} service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  ignore_errors: yes

- name: delete configuration directories
  file:
    path: "{{ config_dir }}"
    state: absent

- name: delete data directories
  file:
    path: "{{ data_dir }}"
    state: absent

- name: delete service file
  file:
    path: "/lib/systemd/system/{{ service_name }}.service"
    state: absent

- name: call 'sudo systemctl daemon-reload'
  shell:
    cmd: "sudo systemctl daemon-reload"
