---
- name: MySQL-python
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    - "python-mysqldb"
    - "python3-pip"
  tags: 
    demo

- name: pip3 install pymysql
  pip:
    name: pymysql
    state: present