apiVersion: v1
kind: Service
metadata:
  labels:   #此处label要和上一步创建的servicemonitor对象的seletor匹配
    app: exporter-es
    component: es-exporter
  name: kube-prometheus-exporter-es
  namespace: kubesphere-monitoring-system
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9114
    protocol: TCP
    targetPort: 9114
