- name: install dependencies libs
  yum:
    name:
      - make
      - autoconf
      - gcc
      - gcc-c++
      - pcre-devel
      - openssl-devel
      - zlib-devel
    state: present

- name: create group for redis
  group:
    name: redis
    state: present

- name: crete user for redis
  user:
    name: redis
    group: redis
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: setup sysctl parameters
  notify:
    - call 'sudo sysctl -p'
  blockinfile:
    path: /etc/sysctl.conf
    marker: "# {mark} 由Ansible添加"
    marker_begin: "begin"
    marker_end: "end"
    block: |
      vm.overcommit_memory = 1
