- name: create group 'mongod'
  group:
    name: mongod
    state: present

- name: crete user 'mongod'
  user:
    name: mongod
    group: mongod
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: install dependencies libs
  yum:
    name:
      - libcurl
      - openssl
      - xz-libs
    state: present

- name: update /etc/security/limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    marker: "# {mark} 由Ansible添加"
    marker_begin: "begin"
    marker_end: "end"
    block: |
      mongod soft noproc 65535
      mongod hard noproc 65535

- name: disable transparent huge pages
  shell:
    cmd: "{{ item }}"
  with_items:
    - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    - "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  changed_when: false
