- name: install zabbix-server
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-get
      - zabbix-web-mysql
      - zabbix-java-gateway
    state: present

- name: copy zabbix server configuration file
  template:
    src: server/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
  notify: restart zabbix-server service

- name: copy zabbix java gateway configuration file
  template:
    src: server/zabbix_java_gateway.conf.j2
    dest: /etc/zabbix/zabbix_java_gateway.conf
    owner: root
    group: root
  notify: restart zabbix-java-gateway service

- name: copy nginx configuration file
  template:
    src: nginx/zabbix.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
    owner: root
    group: root
  notify: restart nginx service

- name: copy php-fpm configuration file
  template:
    src: php/zabbix.conf.j2
    dest: /etc/php-fpm.d/zabbix.conf
    owner: root
    group: root
  notify: restart php-fpm service

- name: copy alert scripts
  template:
    src: "alertscripts/{{ item }}.j2"
    dest: "/usr/lib/zabbix/alertscripts/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - ScriptEmail.sh

- name: start zabbix-server service
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: start zabbix-java-gateway service
  service:
    name: zabbix-java-gateway
    state: started
    enabled: yes

- name: start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
