---
 - name: Install | MySQL pxc requirements
   yum: name={{ item }} state=present
   with_items:
    - "openssl"
    - "asio-devel"
    - "ncurses-devel"
    - "readline-devel"
    - "pam-devel"
    - "libaio-devel"
    - "numactl-devel"
    - "socat"
   failed_when: no
