apiVersion: v1
kind: Service
metadata:
  labels:   #此处label要和上一步创建的servicemonitor对象的seletor匹配
    app: exporter-nacos
    component: nacos-exporter
  name: kube-prometheus-exporter-nacos
  namespace: kubesphere-monitoring-system
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8848
    protocol: TCP
    targetPort: 8848