apiVersion: v1
kind: Endpoints
metadata:
    name: kube-prometheus-exporter-mongodb #此处name要和上一步创建的service对象name相同
    namespace: kubesphere-monitoring-system
    labels:
        k8s-app: mongodb-metrics
subsets:
- addresses:
  - ip: 10.2.115.232
  - ip: 10.2.100.81
  - ip: 10.2.132.223
  ports:
    - name: metrics
      port: 9216
      protocol: TCP
