---
- hosts: edgevpn
  user: root
  # become: true
  gather_facts: no
  tasks:
    - name: Stop and disable edgevpn service
      service:
        name:    edgevpn.service
        enabled: no
        state:   stopped
      register: edgevpn_service_result
      failed_when: "edgevpn_service_result is failed and 'Could not find the requested service' not in edgevpn_service_result.msg"

    - name: Remove edgevpn systemd file
      file:
        path: /etc/systemd/system/edgevpn.service
        state: absent

    - name: Remove edgevpn bin dir 
      file:
        state: absent
        path: /opt/edgevpn/

    - name: Remove edgevpn data on disk (Dangerous !!!!!!!!!!!!!!!!!)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/systemd/system/edgevpn.service
