apiVersion: v1
kind: Endpoints
metadata:
    name: kube-prometheus-exporter-redis #此处name要和上一步创建的service对象name相同
    namespace: kubesphere-monitoring-system
    labels:
        k8s-app: redis-metrics
subsets:
- addresses:
  - ip: 10.2.114.192
  - ip: 10.2.107.94
  - ip: 10.2.159.107
  ports:
    - name: metrics
      port: 9121
      protocol: TCP