- name: stop and disable {{ service_name }}
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  ignore_errors: yes

- name: delete files or directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/logrotate.d/{{ service_name }}"
    - "/lib/systemd/system/{{ service_name }}.service"
    - "{{ config_dir }}/{{ mongod_config_file }}"
    - "/etc/tmpfiles.d/mongodb.conf"
    - "{{ log_dir }}"
    - "{{ pid_dir }}"
    - "{{ data_dir }}"
    - "{{ install_dir }}/keys"

- name: call 'sudo systemctl daemon-reload'
  shell:
    cmd: "sudo systemctl daemon-reload"
  changed_when: no
