---
- name: Init hdfs path
  shell: su {{ user }} -c "hadoop fs -mkdir -p {{ item }}"
  with_items:
    - "{{ spark_hdfs_path }}"

- name: Change Authority
  shell: su {{ user }} -c "hadoop fs -chmod -R 755 {{ item }}"
  with_items:
    - "{{ spark_hdfs_path }}"