- name: create group 'mongod'
  group:
    name: mongod
    state: present

- name: crete user 'mongod'
  user:
    name: mongod
    group: mongod
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: install dependencies libs
  yum:
    name:
      - libcurl
      - openssl
      - xz-libs
    state: present

- name: disable transparent huge pages
  shell:
    cmd: "{{ item }}"
  with_items:
    - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    - "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  changed_when: false
