- hosts: redis
  become: yes
  gather_facts: yes
  vars:
    # SSH 用户
    ansible_user: root
    # SSH 密码
    #ansible_ssh_pass: root1234
    # sudo 提权密码
    #ansible_sudo_pass: root1234
    # Redis 编译好的二进制文件目录
    bin_dir: ./redis-6.2.7/bin-ubuntu18
    # 安装目录
    install_dir: /opt/middleware
    # 主实例端口
    master_port: 6379
    # 从实例端口
    slave_port: 6380
    # Redis 密码
    password: thundersoft-redis
    # 集群副本数
    cluster_replicas: 1
  roles:
  # 初始化环境
  - role: init
    tags: init
  # 配置
  - role: configure_service
    tags: configure_service
  # 启动服务
  - role: start_service
    tags: start_service

 