- name: install nginx
  yum:
    name:
      - nginx
      - httpd-tools
    state: present

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx service

- name: create extra configure dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/ssl
    - /etc/nginx/htpasswd

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
    mode: '0644'
  loop:
    - yingzhuo.com.conf
    - yingzhuo.com.crt
    - yingzhuo.com.key
  notify:
    - restart nginx service

- name: copy password files
  copy:
    src: "yingzhuo.com.password"
    dest: "/etc/nginx/htpasswd/yingzhuo.com.password"
    mode: '0644'
  notify:
    - restart nginx

- name: startup nginx
  service:
    name: nginx
    state: started
    enabled: yes
