apiVersion: v1
kind: Endpoints
metadata:
    name: kube-prometheus-exporter-nacos #此处name要和上一步创建的service对象name相同
    namespace: kubesphere-monitoring-system
    labels:
        k8s-app: nacos-metrics
subsets:
- addresses:
  - ip: 10.2.107.86
  - ip: 10.2.119.125
  - ip: 10.2.156.187
  ports:
    - name: metrics
      port: 8848
      protocol: TCP