apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: exporter-nacos
    component: nacos-exporter
    prometheus: kube-prometheus  # 此处label要和prometheus的crd的serviceMonitorSelector匹配
  name: kube-prometheus-exporter-nacos
  namespace: kubesphere-monitoring-system
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /nacos/actuator/prometheus
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kubesphere-monitoring-system
  selector:
    matchLabels:
      app: exporter-nacos
      component: nacos-exporter
