- name: stop {{ service_name }} service
  service:
    name: "{{ service_name }}"
    state: stopped
    enabled: no
  ignore_errors: yes

- name: remove systemctl config file
  file:
    path: "/lib/systemd/system/{{ service_name }}.service"
    state: absent

- name: call 'sudo systemctl daemon-reload'
  shell:
    cmd: "sudo systemctl daemon-reload"

- name: remove data dir
  file:
    path: "{{ data_dir }}"
    state: absent

- name: remove config dir
  file:
    path: "{{ config_dir }}"
    state: absent

- name: remove log dir
  file:
    path: "{{ log_dir }}"
    state: absent
