---
- hosts: minio
  user: root
  # become: true
  gather_facts: no
  tasks:
    - name: Stop and disable minio service
      service:
        name:    minio.service
        enabled: no
        state:   stopped
      register: minio_service_result
      failed_when: "minio_service_result is failed and 'Could not find the requested service' not in minio_service_result.msg"

    - name: Remove minio systemd file
      file:
        path: /etc/systemd/system/minio.service
        state: absent

    - name: Remove minio bin dir 
      file:
        state: absent
        path: /opt/minio/

    - name: Remove minio data on disk (Dangerous !!!!!!!!!!!!!!!!!)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /mnt/data2/.minio.sys/
        - /mnt/data2/bucket1/
        - /mnt/data2/bucket2/
        - /mnt/data3/.minio.sys/
        - /mnt/data3/bucket1/
        - /mnt/data3/bucket2/