apiVersion: v1
kind: Service
metadata:
  labels:   #此处label要和上一步创建的servicemonitor对象的seletor匹配
    app: exporter-mysql
    component: mysql-exporter
  name: kube-prometheus-exporter-mysql
  namespace: kubesphere-monitoring-system
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: 9104
