- name: install dependencies
  yum:
    name:
      - libcurl
      - openssl
      - xz-libs
    state: present

- name: create group 'mongod'
  group:
    name: mongod
    state: present

- name: crete user 'mongod'
  user:
    name: mongod
    group: mongod
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: update /etc/security/limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    marker: "# {mark} 由Ansible添加"
    marker_begin: "begin"
    marker_end: "end"
    block: |
      mongod soft noproc 65535
      mongod hard noproc 65535

- name: disable transparent huge pages
  shell:
    cmd: "{{ item }}"
  with_items:
    - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    - "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  changed_when: false

- name: create directores for data files
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
  with_items:
    - "{{ data_dir }}"

- name: create directores for key files
  file:
    path: "{{ install_dir }}/keys"
    state: directory
    owner: mongod
    group: mongod

- name: copy key files
  copy:
    src: "mongodb.key"
    dest: "{{ install_dir }}/keys/mongodb.key"
    owner: mongod
    group: mongod
    mode: "0400"

- name: create directores for log files
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
  with_items:
    - "{{ log_dir }}"

- name: create directores for pid files
  file:
    path: "{{ item }}"
    state: directory
    owner: mongod
    group: mongod
  with_items:
    - "{{ pid_dir }}"

- name: copy tmpfiles recreate configuration file
  template:
    src: tmpfiles.mongodb.conf.j2
    dest: /etc/tmpfiles.d/mongodb.conf
    owner: root
    group: root

- name: create directores for configuration files
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ config_dir }}"

- name: copy configuration file for mongod
  template:
    src: mongod.yml.j2
    dest: "{{ config_dir }}/{{ mongod_config_file }}"
    owner: root
    group: root
  notify:
    - restart and enable {{ service_name }} service

- name: copy configuration file for systemctl
  template:
    src: mongod-replica-set.service.j2
    dest: /lib/systemd/system/{{ service_name }}.service
    owner: root
    group: root
  notify:
    - call 'sudo systemctl daemon-reload'

- name: copy configuration file for logrotate mongod
  template:
    src: mongod.logrotate.j2
    dest: "/etc/logrotate.d/{{ service_name }}"
    owner: root
    group: root

- name: start and enable {{ service_name }} service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
